# Generated by Django 2.2.6 on 2019-10-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_participantes_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='participantes',
        ),
    ]
